<?php

// config for Votapil/VotaCrudGenerator
return [

    /*
    |--------------------------------------------------------------------------
    | Default Namespaces
    |--------------------------------------------------------------------------
    |
    | These namespaces are used when generating files. You can override
    | them per-command call using the --namespace option.
    |
    */
    'namespaces' => [
        'model' => 'App\\Models',
        'controller' => 'App\\Http\\Controllers',
        'request' => 'App\\Http\\Requests',
        'resource' => 'App\\Http\\Resources',
        'policy' => 'App\\Policies',
        'factory' => 'Database\\Factories',
    ],

    /*
    |--------------------------------------------------------------------------
    | What to Generate
    |--------------------------------------------------------------------------
    |
    | Toggle which files should be generated by default.
    | All of these can be overridden per-command with --no-{type} flags.
    |
    */
    'generate' => [
        'model' => true,
        'controller' => true,
        'store_request' => true,
        'update_request' => true,
        'resource' => true,
        'policy' => true,
        'factory' => true,
        'routes' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Smart Detection
    |--------------------------------------------------------------------------
    |
    | When enabled, the generator will inspect the DB schema to auto-detect
    | soft deletes (deleted_at column), timestamps, and relationships (FK).
    |
    */
    'detect' => [
        'soft_deletes' => true,
        'timestamps' => true,
        'relationships' => true,
        'casts' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Route Configuration
    |--------------------------------------------------------------------------
    */
    'route_file' => 'routes/api.php',
    'route_prefix' => '',

    /*
    |--------------------------------------------------------------------------
    | Optional Packages Integration
    |--------------------------------------------------------------------------
    |
    | If these packages are installed, generated code will integrate with them.
    |
    */
    'packages' => [
        'spatie_query_builder' => false, // spatie/laravel-query-builder
    ],

    /*
    |--------------------------------------------------------------------------
    | Controller Style
    |--------------------------------------------------------------------------
    |
    | 'api' — generates API-only controllers (JSON responses)
    |
    */
    'controller_style' => 'api',

];
